Repository Tinytown/tinytown-react-app, pull requests merged in 2020-09, with the labels that each got.

#34 i33: Change Status Bar Style
  App.js
Labels: enhancement

#29 i23: Add Splash Screen to iOS / Android
  App.js
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/tinytown/MainActivity.java
  android/app/src/main/java/com/tinytown/SplashActivity.java
  android/app/src/main/res/drawable-hdpi/splash_icon.png
  android/app/src/main/res/drawable-mdpi/splash_icon.png
  android/app/src/main/res/drawable-xhdpi/splash_icon.png
  android/app/src/main/res/drawable-xxhdpi/splash_icon.png
  android/app/src/main/res/drawable-xxxhdpi/splash_icon.png
  android/app/src/main/res/drawable/background_splash.xml
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/styles.xml
  assets/images/logo.png
  frontend/splash/index.js
  ios/Podfile.lock
  ios/tinytown/AppDelegate.m
  ios/tinytown/Base.lproj/LaunchScreen.xib
  ios/tinytown/Images.xcassets/SplashIcon.imageset/Contents.json
  ios/tinytown/Images.xcassets/SplashIcon.imageset/splash_icon.png
  ios/tinytown/Images.xcassets/SplashIcon.imageset/splash_icon@2x.png
  ios/tinytown/Images.xcassets/SplashIcon.imageset/splash_icon@3x.png
  ios/tinytown/Info.plist
  package.json
  yarn.lock
Labels: enhancement

#30 i20: Add Style Variables
  CONTRIBUTING.md
  frontend/splash/index.js
  frontend/styles/color.js
  frontend/styles/index.js
  frontend/styles/shapes.js
  frontend/styles/typography.js
Labels: code health

#35 i25: Floating Action Button
  frontend/components/fab.js
Labels: enhancement

#31 i19: Add Marker for Current User Location
  frontend/assets/fonts/Nunito/Nunito-BlackItalic.ttf
  frontend/assets/fonts/Nunito/Nunito-Bold.ttf
  frontend/assets/fonts/Nunito/Nunito-Regular.ttf
  frontend/assets/fonts/NunitoSans/NunitoSans-Black.ttf
  frontend/assets/img/user_marker.png
  frontend/assets/svg/ic_crosshairs_24dp.js
  frontend/assets/svg/index.js
  frontend/components/fab.js
  frontend/mapbox/fixtures/current-location-icon.js
  frontend/mapbox/index.js
  frontend/splash/index.js
  ios/Podfile.lock
  ios/tinytown.xcodeproj/project.pbxproj
  ios/tinytown.xcodeproj/xcshareddata/xcschemes/tinytown.xcscheme
  ios/tinytown/Info.plist
  package.json
  react-native.config.js
  yarn.lock
Labels: feature
